# to use starship see https://starship.rs/

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = " "

[buf]
symbol = " "

[bun]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[c]
format = '\[[$symbol($version(-$name))]($style)\]'
symbol = " "

[cmake]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'
symbol = " "

[crystal]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[daml]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[deno]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = " "

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
symbol = " "

[elm]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[erlang]
format = '\[[$symbol($version)]($style)\]'

[fennel]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
symbol = " "

[git_metrics]
disabled = false

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[git_commit]
disabled = false
tag_symbol = '  '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[gradle]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[guix_shell]
format = '\[[$symbol]($style)\]'
symbol = " "

[shell]
disabled = false

[haskell]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[haxe]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[hostname]
ssh_symbol = " "
ssh_only = false

[java]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[julia]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[kotlin]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[memory_usage]
disabled = false
threshold = -1
symbol = "󰍛 "
style = 'bold dimmed green'
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
format = '\[[$symbol$project]($style)\]'
symbol = "󰔷 "

[nim]
format = '\[[$symbol($version)]($style)\]'
symbol = "󰆥 "

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'
symbol = " "

[nodejs]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[opa]
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
disabled = false
format = '\[[$symbol]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'
symbol = "󰏗 "

[perl]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[php]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'
symbol = " "

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = " "

[rlang]
symbol = "󰟔 "

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = "󱘗 "

[scala]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[status]
symbol = " "
disabled = false

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
disabled = false
format = '\[[as $symbol]($style)\]'

[swift]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
disabled = false
format = '\[[$time]($style)\]'

[username]
format = '\[[$user]($style)\]'
show_always = true

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[solidity]
format = '\[[$symbol($version)]($style)\]'
